### ISSUE TITLE
Have optionnal parameter

### ISSUE THREAD

**Issue by jgomeslf** [usebutton/DeepLinkKit#58] opened 2015-06-08 14:17 UTC
Hi,

I would like to track a campaign code in the deep link to see where some of the users come from.
So I can have something like @"/account" but also @"/account/:campaign_code".
It would be nice to do that !

**Comment by wessmith** [comment] 2015-09-16 16:26
We don't currently support regex matching on the URL as a whole, only individual path components. Sounds like a good idea though. For now, you could register two handlers with the more specific route first.

```objc
router[@"/account/:campaign_code"] = ^(DPLDeepLink *link) {
    // run some code
};

router[@"/account"] = ^(DPLDeepLink *link) {
    // run some code
};
```

Or even:
```objc
void (^accountHandler)(DPLDeepLink *) = ^(DPLDeepLink *link) {
    // run some code
};
router[@"/account/:campaign_code"] = accountHandler;
router[@"/account"] = accountHandler;
```

**Comment by wessmith** [comment] 2015-09-16 16:29
Closing as duplicate of #63

**Closed by wessmith** 2015-09-16 16:29 UTC
